#Libraries

numpy

In [2]:
#import numpy
import numpy as np

In [3]:
l1= [1,2,3,4,5]
arr1=np.array(l1)

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [8]:
# 1d array
arr1.shape

(5,)

In [9]:
#multinested array
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=[11,12,13,14,15]

arr2=np.array([l1,l2,l3])

In [10]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
arr2.shape

(3, 5)

In [13]:
arr2.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [14]:
arr2.shape

(3, 5)

In [17]:
arr2.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [18]:
arr2.shape

(3, 5)

In [19]:
arr1

array([1, 2, 3, 4, 5])

In [21]:
arr1[3]

4

In [22]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
#indexing
arr2[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
arr2[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [27]:
arr2[2:,2:4]

array([[13, 14]])

In [33]:
arr3=np.arange(0,13,step=2)

In [34]:
arr3

array([ 0,  2,  4,  6,  8, 10, 12])

In [37]:
#equal spaced in between numbers
arr4=np.linspace(0,10,20)

In [38]:
type(arr4)

numpy.ndarray

In [39]:
arr4

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [42]:
#broadcasting
arr3

array([ 0,  2,  4,  6,  8, 10, 12])

In [50]:
arr3[3:6]=57
arr3

array([ 0,  2,  4, 57, 57, 57, 12])

In [49]:
l4=[1,2,3,4,5,6,7]
arr5=np.array(l4)
arr5

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
arr5[3:6]=67
arr5

array([ 1,  2,  3, 67, 67, 67,  7])

In [52]:
arr3

array([ 0,  2,  4, 57, 57, 57, 12])

In [57]:
#copy array
arr6=arr3.copy()

In [59]:
arr6[3:6]=47
arr6

array([ 0,  2,  4, 47, 47, 47, 12])

In [60]:
arr3

array([ 0,  2,  4, 57, 57, 57, 12])

In [61]:
arr3*2

array([  0,   4,   8, 114, 114, 114,  24])

In [62]:
arr3<13

array([ True,  True,  True, False, False, False,  True])

In [3]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [65]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [4]:
np.random.rand(3,3)

array([[0.60866571, 0.2329472 , 0.6790424 ],
       [0.56857054, 0.26581779, 0.05819651],
       [0.1528301 , 0.61455173, 0.73720393]])

In [6]:
arr7=np.random.randn(4,4)
arr7

array([[-0.1804199 , -0.29063704, -1.10624169, -0.30917827],
       [-0.33192042, -0.87681401,  0.19096077,  0.62159647],
       [-1.05684426,  0.0523281 , -2.04686726,  1.26789261],
       [ 1.0214953 , -0.06861367,  1.59273531,  2.19616826]])

In [74]:
np.random.randint(0,200,16)

array([110, 175,  24,  45, 194, 108, 147,  49,  59,  71,  24, 159, 103,
        14,  24,  92])

In [75]:
np.random.randint(0,200,16).reshape(4,4)

array([[149,  88, 117,   6],
       [133, 163,  72,  24],
       [132,  28,  34, 151],
       [ 94,  70, 158, 180]])

In [76]:
np.random.random_sample((1,5))

array([[0.43106521, 0.48452482, 0.07378043, 0.49728133, 0.64725412]])

#pandas

In [5]:
import pandas as pd
import numpy as np

In [5]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['column1','column2','column3','column4'])

In [6]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [7]:
df.to_csv('test1.csv')

In [8]:
#accessing elements

df.loc['row1']

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int32

In [22]:
df['column3']

row1     2
row2     6
row3    10
row4    14
row5    18
Name: column3, dtype: int32

In [23]:
df[['column3','column4']]

column3  column4
row1        2        3
row2        6        7
row3       10       11
row4       14       15
row5       18       19

In [24]:
type(df[['column3','column4']])

pandas.core.frame.DataFrame

In [9]:
type(df.loc['row1'])

pandas.core.series.Series

In [10]:
df.iloc[0:3,0:2]

column1  column2
row1        0        1
row2        4        5
row3        8        9

In [11]:
type(df.iloc[0:3,0:2])

pandas.core.frame.DataFrame

In [12]:
df.iloc[1:,1:]

column2  column3  column4
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [14]:
#dataframe to array
df.iloc[1:,1:].values

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [15]:
df.iloc[1:,1:].values.shape

(4, 3)

In [27]:
df.isnull()

column1  column2  column3  column4
row1    False    False    False    False
row2    False    False    False    False
row3    False    False    False    False
row4    False    False    False    False
row5    False    False    False    False

In [26]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [18]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [19]:
#for categorical data types
df['column1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: column1, dtype: int64

In [20]:
df['column1'].unique()

array([ 0,  4,  8, 12, 16])

In [28]:
##Reading files
## df=pd.read.csv('file.csv')

test_df=pd.read_csv('test1.csv', sep=',')

In [30]:
test_df.head()

Unnamed: 0  column1  column2  column3  column4
0       row1        0        1        2        3
1       row2        4        5        6        7
2       row3        8        9       10       11
3       row4       12       13       14       15
4       row5       16       17       18       19

In [32]:
test_df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [34]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5 non-null      object
 1   column1     5 non-null      int64 
 2   column2     5 non-null      int64 
 3   column3     5 non-null      int64 
 4   column4     5 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 328.0+ bytes


In [36]:
df[df['column3']>9]

column1  column2  column3  column4
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [2]:
#reading files as dataframes
df_1=pd.read_csv('mercedesbenz.csv')

In [3]:
df_1.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [4]:
df_1.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [5]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [8]:
df_1.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [10]:
df_1['X1'].value_counts()

aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
w      52
z      46
u      37
e      33
m      32
t      31
h      29
y      23
f      23
j      22
n      19
k      17
p       9
g       6
d       3
q       3
ab      3
Name: X1, dtype: int64

In [11]:
df_1[df_1['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

In [6]:
from io import StringIO, BytesIO

In [10]:
data= ('col1,col2,col3\n'
      'x,y,1\n'
      'a,b,2\n'
      'c,d,3')

In [11]:
type(data)

str

In [14]:
##
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [15]:
#selecting columns
df_2=pd.read_csv(StringIO(data), usecols=['col1','col3'])
df_2

col1  col3
0    x     1
1    a     2
2    c     3

In [17]:
df_2.to_csv('usecolTest.csv')

In [18]:
data2= ('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11,12')

In [20]:
print(data2)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12


In [23]:
df3=pd.read_csv(StringIO(data2),dtype={'a':'Int64', 'b':float, 'c':int})

In [26]:
df3

a     b   c   d
0  1   2.0   3   4
1  5   6.0   7   8
2  9  10.0  11  12

In [27]:
type(df3)

pandas.core.frame.DataFrame

In [29]:
df3['b']

0     2.0
1     6.0
2    10.0
Name: b, dtype: float64

In [30]:
df3['c']

0     3
1     7
2    11
Name: c, dtype: int32

In [31]:
df3['b'][1]

6.0

In [33]:
type(df3['b'][1])

numpy.float64

In [34]:
df3.dtypes

a      Int64
b    float64
c      int32
d      int64
dtype: object

In [48]:
#Setting index column (index_col)
data3= ('Index,a,b,c,d\n'
      'X,1,2,3,4\n'
      'Y,5,6,7,8\n'
      'Z,9,10,11,12')

In [49]:
df4=pd.read_csv(StringIO(data3), index_col=0)
df4

a   b   c   d
Index               
X      1   2   3   4
Y      5   6   7   8
Z      9  10  11  12

In [50]:
df5=pd.read_csv(StringIO(data3), index_col=False)
df5

Index  a   b   c   d
0     X  1   2   3   4
1     Y  5   6   7   8
2     Z  9  10  11  12

In [51]:
df6=pd.read_csv(StringIO(data3), usecols=['b','c','d'], index_col=0)
df6

c   d
b         
2    3   4
6    7   8
10  11  12

In [52]:
df6=pd.read_csv(StringIO(data3), usecols=['Index','b','c','d'], index_col=0)
df6

b   c   d
Index            
X       2   3   4
Y       6   7   8
Z      10  11  12

In [53]:
##Read Json files

In [54]:
Dataj = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(Dataj)

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [55]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [56]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [57]:
df.to_csv('wine.csv')

In [58]:
##
df.to_json(orient="index")

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3

In [62]:
df8=df.to_json(orient="records")
df8

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"

In [63]:
## Read html

In [66]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'

dfs = pd.read_html(url)

In [68]:
dfs[0]

Bank NameBank           CityCity StateSt  CertCert  \
0                    Almena State Bank             Almena      KS     15426   
1           First City Bank of Florida  Fort Walton Beach      FL     16748   
2                 The First State Bank      Barboursville      WV     14361   
3                   Ericson State Bank            Ericson      NE     18265   
4     City National Bank of New Jersey             Newark      NJ     21111   
..                                 ...                ...     ...       ...   
558                 Superior Bank, FSB           Hinsdale      IL     32646   
559                Malta National Bank              Malta      OH      6629   
560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
561  National State Bank of Metropolis         Metropolis      IL      3815   
562                   Bank of Honolulu           Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0                            Equity Bank    October 23, 2020     10538  
1              United Fidelity Bank, fsb    October 16, 2020     10537  
2                         MVB Bank, Inc.       April 3, 2020     10536  
3             Farmers and Merchants Bank   February 14, 2020     10535  
4                        Industrial Bank    November 1, 2019     10534  
..                                   ...                 ...       ...  
558                Superior Federal, FSB       July 27, 2001      6004  
559                    North Valley Bank         May 3, 2001      4648  
560  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
561              Banterra Bank of Marion   December 14, 2000      4646  
562                   Bank of the Orient    October 13, 2000      4645  

[563 rows x 7 columns]

In [69]:
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs = pd.read_html(url_mcc, match='Country', header=0)
dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [70]:
#Reading Excel

In [72]:
df_excel=pd.read_excel('Worksheet in eq.xlsx')
df_excel

customer_id  customer_age     job_type  marital  education default  \
0        id_32289          34.0  blue-collar  married  secondary      no   
1        id_40992          41.0  blue-collar  married    primary      no   
2        id_41178          57.0  blue-collar  married    primary      no   
3        id_35102          37.0   management  married   tertiary      no   
4        id_34750          29.0   technician  married  secondary      no   
...           ...           ...          ...      ...        ...     ...   
23875    id_27290          58.0       admin.  married  secondary      no   
23876    id_20428          51.0   management  married   tertiary      no   
23877    id_44679          41.0   unemployed  married    primary      no   
23878     id_4841          48.0     services  married  secondary      no   
23879     id_1723          38.0   technician   single   tertiary      no   

       balance housing_loan personal_loan communication_type  day_of_month  \
0        934.0           no           yes           cellular            18   
1       1352.0          yes            no           cellular            13   
2        495.0           no            no           cellular            18   
3        650.0          yes           NaN            unknown            26   
4        265.0          yes            no           cellular            19   
...        ...          ...           ...                ...           ...   
23875    567.0          yes            no           cellular             2   
23876   1072.0           no            no            unknown            20   
23877    242.0          yes            no            unknown            23   
23878   2699.0           no            no           cellular            11   
23879   1045.0           no            no           cellular            18   

      month  last_contact_duration  num_contacts_in_campaign  \
0       nov                    704                       2.0   
1       may                    893                       2.0   
2       aug                    796                       4.0   
3       may                    880                       1.0   
4       aug                    795                       2.0   
...     ...                    ...                       ...   
23875   feb                    993                       2.0   
23876   jun                    855                       7.0   
23877   may                    883                       2.0   
23878   aug                    803                       6.0   
23879   aug                    796                      10.0   

       num_contacts_prev_campaign prev_campaign_outcome  \
0                               1                 other   
1                               0               unknown   
2                               0               unknown   
3                               0               unknown   
4                               0               unknown   
...                           ...                   ...   
23875                           3                 other   
23876                           0               unknown   
23877                           0               unknown   
23878                           0               unknown   
23879                           0               unknown   

       term_deposit_subscribed  
0                            0  
1                            0  
2                            1  
3                            0  
4                            0  
...                        ...  
23875                        0  
23876                        0  
23877                        0  
23878                        0  
23879                        0  

[23880 rows x 17 columns]

In [76]:
##Pickling
df_excel.to_pickle('df_excel')
df=pd.read_pickle('df_excel')
df.head()

customer_id  customer_age     job_type  marital  education default  balance  \
0    id_32289          34.0  blue-collar  married  secondary      no    934.0   
1    id_40992          41.0  blue-collar  married    primary      no   1352.0   
2    id_41178          57.0  blue-collar  married    primary      no    495.0   
3    id_35102          37.0   management  married   tertiary      no    650.0   
4    id_34750          29.0   technician  married  secondary      no    265.0   

  housing_loan personal_loan communication_type  day_of_month month  \
0           no           yes           cellular            18   nov   
1          yes            no           cellular            13   may   
2           no            no           cellular            18   aug   
3          yes           NaN            unknown            26   may   
4          yes            no           cellular            19   aug   

   last_contact_duration  num_contacts_in_campaign  \
0                    704                       2.0   
1                    893                       2.0   
2                    796                       4.0   
3                    880                       1.0   
4                    795                       2.0   

   num_contacts_prev_campaign prev_campaign_outcome  term_deposit_subscribed  
0                           1                 other                        0  
1                           0               unknown                        0  
2                           0               unknown                        1  
3                           0               unknown                        0  
4                           0               unknown                        0