### List Exercises

In [1]:
expense=[2200,2350,2600,2130,2190]

In [2]:
expense[1]-expense[0]

150

In [3]:
expense[0]+expense[1]+expense[2]

7150

In [4]:
sum(expense[:3])

7150

In [5]:
for x in expense:
    if x==2000:
        print ('True')
    else:
        print('False')


False
False
False
False
False


In [6]:
2000 in expense

False

In [7]:
expense.append(1980)

In [8]:
expense

[2200, 2350, 2600, 2130, 2190, 1980]

In [9]:
expense[3] = 2130-200

In [10]:
expense

[2200, 2350, 2600, 1930, 2190, 1980]

In [11]:
heros=['spider man','thor','hulk','iron man','captain america']

In [12]:
heros.append('black panther')

In [13]:
heros

['spider man', 'thor', 'hulk', 'iron man', 'captain america', 'black panther']

In [14]:
heros.pop(5)

'black panther'

In [15]:
heros

['spider man', 'thor', 'hulk', 'iron man', 'captain america']

In [16]:
heros.insert(3,'black panther')

In [17]:
heros

['spider man', 'thor', 'hulk', 'black panther', 'iron man', 'captain america']

In [18]:
heros[1:3]= ['doctor strange']

In [19]:
heros

['spider man',
 'doctor strange',
 'black panther',
 'iron man',
 'captain america']

In [20]:
heros[2]

'black panther'

In [21]:
heros.sort()

In [22]:
heros

['black panther',
 'captain america',
 'doctor strange',
 'iron man',
 'spider man']

### if...

In [23]:
india = ["mumbai", "banglore", "chennai", "delhi"]
pakistan = ["lahore","karachi","islamabad"]
bangladesh = ["dhaka", "khulna", "rangpur"]

In [24]:
city = input('Enter city name: ')

if city in india:
    print('{} is in india'.format(city))
elif city in pakistan:
    print('{} is in pakistan'.format(city))
else:
    print('{} is in bangladesh'.format(city))

Enter city name: dhaka
dhaka is in bangladesh


In [25]:
city1= input('city 1:')
city2= input('city 2:')

if city1 in india and city2 in india:
    print('{}, {} both in india'.format(city1,city2))
if city1 in pakistan and city2 in pakistan:
    print('{}, {} both in pakistan'.format(city1,city2))
if city1 in bangladesh and city2 in bangladesh:
    print('{}, {} both in india'.format(city1,city2))
else:
    print('{}, {} not in same country'.format(city1,city2))

city 1:mumbai
city 2:karachi
mumbai, karachi not in same country


In [26]:
sugar= input('Enter fasting sugar level:')
sugar= float(sugar)
if sugar < 80:
    print('low sugar level')
elif sugar > 100:
    print('high sugar level')
else:
    print('normal sugar level')

Enter fasting sugar level:120
high sugar level


### for

In [27]:
result = ["heads","tails","tails","heads","tails","heads","heads","tails","tails","tails"]

In [28]:
count = 0
for i in result:
    if i=='heads':
        count=count+1
print('head count is:', count)


head count is: 4


In [29]:
for x in range(1,10):
    if x%2 != 0:
        print (x*x)

1
9
25
49
81


In [30]:
expense_list = [2340, 2500, 2100, 3100, 2980]
month_list = ['jan','feb','mar','apr','may']

In [31]:
x =input('Enter expense amount:')
x= int(x)

for i in range(len(expense_list)):
    if x == expense_list[i]:
        month=i
        break

if month != -1:
    print ('You spent {} in {}'.format(x,month_list[i]))
else:
    print ('you didn\'t spend {} on any month'.format(x))

Enter expense amount:3100
You spent 3100 in apr


In [32]:
for i in range(5):
    print(f"You ran {i+1} miles")
    tired = input("Are you tired? ")
    if tired == 'yes':
        break

if i == 4:
    print("Congrats! You finished 5 km race!")
else:
    print("loser, you did not finish")


You ran 1 miles
Are you tired? no
You ran 2 miles
Are you tired? no
You ran 3 miles
Are you tired? no
You ran 4 miles
Are you tired? yes
loser, you did not finish


In [33]:
for i in range(1,6):
    s = ''
    for j in range(i):
        s += '*'
    print(s)

*
**
***
****
*****


In [34]:
for i in range(1,6):
    fig= i*'*'
    print(fig)

*
**
***
****
*****


In [35]:
s = ''
for i in range(1,6):
    s += '*'
    print(s)

*
**
***
****
*****


### function

In [36]:
def triangle_area(base,height):
    area = (1/2)*base*height
    print('Area of triangle is: ', area)

In [37]:
triangle_area(5,6)

Area of triangle is:  15.0


In [38]:
def triangle_area():
    base= input('enter base:' )
    base=int(base)
    height= input('enter height:' )
    height=int(height)
    area = (1/2)*base*height
    print('Area of triangle is: ', area)

In [39]:
triangle_area()

enter base:6
enter height:4
Area of triangle is:  12.0


In [40]:
def triangle_area():
    base= int(input('enter base:' ))
    height= int(input('enter height:' ))
    area = (1/2)*base*height
    print('Area of triangle is: ', area)

In [41]:
def area():
    shape = str(input("Enter shape: 'traingle'/'rectangle'  "))
    if shape== 'triangle':
        base= int(input('enter base:' ))
        height= int(input('enter height:' ))
        area = (1/2)*base*height
        print('Area of triangle is: ', area)
        
    elif shape== 'rectangle':
        length= int(input('enter length:' ))
        width= int(input('enter width:' ))
        rectangle_area=length*width
        print('Area of rectangle is: ', rectangle_area)
    else:
        print('Shape not recognised. Please select among options provided')

In [42]:
area()

Enter shape: 'traingle'/'rectangle'  rectangle
enter length:8
enter width:6
Area of rectangle is:  48


In [43]:
def area_k(shape='triangle'):
    if shape== 'rectangle':
        length= int(input('enter length:' ))
        width= int(input('enter width:' ))
        rectangle_area=length*width
        print('Area of rectangle is: ', rectangle_area)
    else:
        base= int(input('enter base:' ))
        height= int(input('enter height:' ))
        area = (1/2)*base*height
        print('Area of triangle is: ', area)

In [44]:
area_k('rectangle')

enter length:6
enter width:3
Area of rectangle is:  18


In [45]:
area_k()

enter base:4
enter height:6
Area of triangle is:  12.0


In [46]:
def print_pattern(num):
    for i in range(0,10):
        if i<=num:
            pattern = i*'*'
            print(pattern)

In [47]:
print_pattern(7)


*
**
***
****
*****
******
*******


### tuples, dictionaries

In [48]:
country_population = {
    'china': 143,
    'india': 136,
    'usa': 32,
    'pakistan': 21
}

In [49]:
def add():
    new_country= input('enter new country name:')
    new_country= new_country.lower()
    
    if new_country in country_population:
        print('it already exists')
    
    else:
        new_population= int(input('enter the population'))
        country_population[new_country]=new_population
        print(country_population)

In [51]:
add()

enter new country name:france
enter the population28
{'china': 143, 'india': 136, 'usa': 32, 'pakistan': 21, 'germany': 25, 'france': 28}


In [52]:
def remove():
    remove_country= input('enter country name to remove from dictionary:')
    if remove_country in country_population:
        country_population.pop(remove_country)
        print(country_population)
    else:
        print ('country doesnt exist in dictionary')

In [53]:
remove()

enter country name to remove from dictionary:usa
{'china': 143, 'india': 136, 'pakistan': 21, 'germany': 25, 'france': 28}


In [54]:
pi= np.pi
pi

<IPython.core.display.Javascript object>

3.141592653589793

In [55]:
def circle_calc():
    r=int(input('Radius of circle:'))
    area= pi*r*r
    circumference = 2*pi*r
    diameter= 2*r
    
    print('diameter of circle:', diameter)
    print('area of circle:', area)
    print('circumference of circle:', circumference)

In [56]:
circle_calc()

Radius of circle:6
diameter of circle: 12
area of circle: 113.09733552923255
circumference of circle: 37.69911184307752


### reading files

In [57]:
import pandas as pd

In [58]:
poem = pd.read_fwf('poem.txt')

In [59]:
poem

Two roads diverged in a yellow wood,
0        And sorry I could not travel both
1        And be one traveler, long I stood
2    And looked down one as far as I could
3     To where it bent in the undergrowth;
4    Then took the other, as just as fair,
5     And having perhaps the better claim,
6   Because it was grassy and wanted wear;
7     Though as for that the passing there
8     Had worn them really about the same,
9        And both that morning equally lay
10    In leaves no step had trodden black.
11   Oh, I kept the first for another day!
12    Yet knowing how way leads on to way,
13   I doubted if I should ever come back.
14     I shall be telling this with a sigh
15          Somewhere ages and ages hence:
16    Two roads diverged in a wood, and I—
17        I took the one less traveled by,
18   And that has made all the difference.

In [60]:
stock=pd.read_csv('stocks.csv')
stock

Company Name  Price  Earnings Per Share   Book Value
0       Reliance   1467                  66          653
1     Tata Steel    391                  89          572
2        Infosys    650                  35          147
3      Axis Bank    739                  19          263
4  Bajaj Finance   4044                  69          341

In [61]:
stock.describe()

Price  Earnings Per Share   Book Value
count     5.000000            5.000000     5.000000
mean   1458.200000           55.600000   395.200000
std    1499.649192           28.138941   211.976886
min     391.000000           19.000000   147.000000
25%     650.000000           35.000000   263.000000
50%     739.000000           66.000000   341.000000
75%    1467.000000           69.000000   572.000000
max    4044.000000           89.000000   653.000000

In [62]:
price= stock['Price'].values
eps= stock['Earnings Per Share'].values


In [63]:
eps

array([66, 89, 35, 19, 69], dtype=int64)

In [64]:
bv=stock.iloc[:,-1].values

In [65]:
bv

array([653, 572, 147, 263, 341], dtype=int64)

In [66]:
price

array([1467,  391,  650,  739, 4044], dtype=int64)

In [67]:
pe= price/eps
pb = price/bv

In [68]:
PE_Ratio = pe.round(2)
PB_Ratio = pb.round(2)

In [69]:
PE_Ratio

array([22.23,  4.39, 18.57, 38.89, 58.61])

In [70]:
PB_Ratio

array([ 2.25,  0.68,  4.42,  2.81, 11.86])

In [71]:
stock

Company Name  Price  Earnings Per Share   Book Value
0       Reliance   1467                  66          653
1     Tata Steel    391                  89          572
2        Infosys    650                  35          147
3      Axis Bank    739                  19          263
4  Bajaj Finance   4044                  69          341

In [72]:
stock['PE_Ratio']=PE_Ratio

In [73]:
stock['PB_Ratio']=PB_Ratio

In [74]:
stock

Company Name  Price  Earnings Per Share   Book Value  PE_Ratio  PB_Ratio
0       Reliance   1467                  66          653     22.23      2.25
1     Tata Steel    391                  89          572      4.39      0.68
2        Infosys    650                  35          147     18.57      4.42
3      Axis Bank    739                  19          263     38.89      2.81
4  Bajaj Finance   4044                  69          341     58.61     11.86

In [75]:
stock.drop(stock.iloc[:, 1:4], inplace = True, axis = 1)

In [76]:
stock

Company Name  PE_Ratio  PB_Ratio
0       Reliance     22.23      2.25
1     Tata Steel      4.39      0.68
2        Infosys     18.57      4.42
3      Axis Bank     38.89      2.81
4  Bajaj Finance     58.61     11.86

In [77]:
stock.to_csv('stockmod.csv')

### Classes

In [78]:
class employee:
    def __init__(self, id, name):
        self.id= id
        self.name=name
        
    def myfunc(self):
        print('hello, i am ', self.name)
        print('id no.: ', self.id)

In [79]:
emp1 = employee(1, 'tom')
emp2 = employee(2, 'jerry')
emp3 = employee(3, 'spike')

In [80]:
emp1.myfunc()

hello, i am  tom
id no.:  1


In [81]:
emp1.id = 4

In [82]:
del emp3.id

In [83]:
del emp3

### inheritance

In [84]:
class Animal:
    def __init__ (self, legs, tail):
        self.legs=legs
        self.tail=tail
        
    def myself (self):
        print('hi, i have {} legs and {} tail'.format(self.legs, self.tail))
        
    def habitat(self):
        habitat = input("Enter habitat 'pet'/'domestic'/'wild' :")
        if  habitat== 'pet':
            print('i am your pet. pet me')
        elif habitat == 'domestic':
            print('i am domestic. i help you')
        elif habitat == 'wild':
            print('i am wild. i might eat you')
        else:
            print('select from options provided')

In [85]:
dog= Animal(2,'1')
spider=Animal(8,'no')

In [86]:
spider.myself()

hi, i have 8 legs and no tail


In [87]:
spider.habitat()

Enter habitat 'pet'/'domestic'/'wild' :wild
i am wild. i might eat you


In [96]:
class Dog(Animal):
    def __init__ (self, legs, tail, breed):
        super().__init__(legs, tail)
        self.breed = breed
    def spcs(self):
        biting = input('Does it bite? :')
        if biting == 'yes':
            print('i am {} and i bite'.format(self.breed))
        else:
            print('i am {} and i do not bite'.format(self.breed))

In [97]:
dbmn=Dog('4', '1', 'doberman')
lbdrtv= Dog('4', '1', 'labrodar retriver')
pug= Dog('4', '1', 'pug')

In [98]:
lbdrtv.habitat()

Enter habitat 'pet'/'domestic'/'wild' :pet
i am your pet. pet me


In [99]:
dbmn.spcs()

Does it bite? :yes
i am doberman and i bite


In [100]:
pug.myself()

hi, i have 4 legs and 1 tail


In [101]:
class Teacher:
    def teachers_action(self):
        print("I can teach")


class Engineer:
    def Engineers_action(self):
        print("I can code")


class Youtuber(Teacher,Engineer):
    pass


In [105]:
xyz=Youtuber()

In [106]:
xyz.Engineers_action()

I can code


In [108]:
xyz.teachers_action()

I can teach


### iterators

In [45]:
def fibonacci(n):
    if n <= 0:
        print("Incorrect input")
        
    elif n == 1:
        return 0
 
    elif n == 2:
        return 1
    
    else:
        return fibonacci(n-1) + fibonacci(n-2)

In [46]:
fibonacci(6)

5

In [47]:
def fib():
    k = input("Enter number of terms:")
    k=int(k)
    n1,n2= 0,1
    if k<=0:
        print('invalid input')
    elif k == 1:
        print(n1)
    elif k == 2:
        print('Sequence:')
        print(n1)
        print(n2)
    else:
        count=0
        print('sequence:')
        while count<k:
            print(n1)
            n3 = n1+n2
            n1=n2
            n2=n3
            count += 1
            

In [48]:
fib()

Enter number of terms:15
sequence:
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377


In [49]:
## nth term fibonacci 

k = input("Enter number of terms:")
k=int(k)
n1,n2= 0,1

if k<=0:
    print('invalid input')
elif k == 1:
    print(n1)
elif k == 2:
    print(n2)
else:
    count=0
    while count<k-1:
        n3 = n1+n2
        n1=n2
        n2=n3
        count += 1
    print(n1)

Enter number of terms:8
13


In [53]:
import datetime

x = datetime.datetime.now()
print(x)

2022-06-09 21:29:37.757869


### generator

In [2]:
## not generator
def sq():
    a=1
    while a<20:
        print (a*a)
        a += 1
    

In [3]:
sq()

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361


In [5]:
def sq_gen():
    a=1
    while True:
        yield a*a
        a+=1

In [7]:
for i in sq_gen():
    if i>300:
        break
    print(i)

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289


In [8]:
def remote_tv():
    yield 'cn'
    yield 'espn'
    yield 'ten'

In [14]:
itr = remote_tv()
itr

<generator object remote_tv at 0x0000022D769DC3C0>

In [16]:
next(itr)

'espn'

In [22]:
def fibo():
    a=0
    b=1
    while True:
        yield a
        c=a+b
        a=b
        b=c
    

In [24]:
for f in fibo():
    if f>200:
        break
    print(f)

0
1
1
2
3
5
8
13
21
34
55
89
144
